INSERT INTO Product(description, unit_price,unit) VALUES('Rice',15.0,'cup');
INSERT INTO Product(description, unit_price,unit) VALUES('Egg',10.0,'pc(s)');
INSERT INTO Product(description, unit_price,unit) VALUES('Tuna',35.0,'can');
INSERT INTO Product(description, unit_price,unit) VALUES('Fried Fish',20.0,'pc(s)');
INSERT INTO Product(description, unit_price,unit) VALUES('Noodles',20.0,'pc(s)');
INSERT INTO Product(description, unit_price,unit) VALUES('Ice Cream',20.0,'cup');
INSERT INTO Product(description, unit_price,unit) VALUES('Yogurt',15.0,'pc(s)');
INSERT INTO Product(description, unit_price,unit) VALUES('Potato Chips',25.0,'pc(s)');
INSERT INTO Product(description, unit_price,unit) VALUES('Water',10.0,'bottle');
INSERT INTO Product(description, unit_price,unit) VALUES('Softdrinks',25.0,'bottle');